function getRandomInt(max) {
    return Math.floor(Math.random() * max);
}

const CONFIG = {
    gameTitle: "Crillion",
    tagline: "September 28, 2026",
    secondsPerQuestion: 45,
}

const QUESTIONS_WEEK_3 = [
    {
        // Local Geography 3.5/5
        prompt: "Name a city you can fly to directly from Boston Logan Airport",
        description: null,
        answers: [
            { 
                answer: "Chicago",
                points: 10,
                accept: ["Chicago"],
                description: null
            },
            { 
                answer: "Washington DC",
                points: 10,
                accept: ["Washington DC", "Washington", "DC"],
                description: null
            },
            { 
                answer: "New York",
                points: 10,
                accept: ["New York", "New York City", "NYC", "NY"],
                description: null,
            },
            { 
                answer: "San Francisco",
                points: 10,
                accept: ["San Francisco", "SF"],
                description: null,
            },
            { 
                answer: "Nantucket",
                points: 60,
                accept: ["Nantucket"],
                description: null,
            },
            { 
                answer: "Atlanta",
                points: 30,
                accept: ["Atlanta"],
                description: null,
            },
            { 
                answer: "Los Angeles",
                points: 10,
                accept: ["Los Angeles", "LA"],
                description: null,
            },
            { 
                answer: "Philidelphia",
                points: 30,
                accept: ["Philly", "Philidelphia"],
                description: null,
            },
            { 
                answer: "Martha's Vineyard",
                points: 85,
                accept: ["Martha's Vineyard", "Marthas Vineyard"],
                description: null,
            },
            { 
                answer: "Orlando",
                points: 60,
                accept: ["Orlando"],
                description: null,
            },            
            { 
                answer: "Denver",
                points: 30,
                accept: ["Denver"],
                description: null,
            },
            { 
                answer: "Baltimore",
                points: 30,
                accept: ["Baltimore"],
                description: null,
            },            
            { 
                answer: "Seattle",
                points: 30,
                accept: ["Seattle"],
                description: null,
            },
            { 
                answer: "Dallas",
                points: 30,
                accept: ["Dallas"],
                description: null,
            },            
            { 
                answer: "Charlotte",
                points: 30,
                accept: ["Charlotte"],
                description: null,
            },
            { 
                answer: "Nashville",
                points: 60,
                accept: ["Nashville"],
                description: null,
            },            
            { 
                answer: "Bar Harbor",
                points: 85,
                accept: ["Bar Harbor", "Bar Harbour"],
                description: "Hey, I know this one!",
            },
            { 
                answer: "London",
                points: 10,
                accept: ["London"],
                description: null,
            },            
            { 
                answer: "Raleigh",
                points: 60,
                accept: ["Raleigh", "Durham"],
                description: null,
            },
            { 
                answer: "Detroit",
                points: 30,
                accept: ["Detroit"],
                description: null,
            },            
            { 
                answer: "Pittsburgh",
                points: 30,
                accept: ["Pittsburgh"],
                description: null,
            },
            { 
                answer: "Toronto",
                points: 10,
                accept: ["Toronto"],
                description: null,
            },            
            { 
                answer: "Tampa Bay",
                points: 60,
                accept: ["Tampa", "Tampa Bay"],
                description: null,
            },
            { 
                answer: "Provincetown",
                points: 85,
                accept: ["Provincetown"],
                description: null,
            },            
            { 
                answer: "San Diego",
                points: 30,
                accept: ["San Diego"],
                description: null,
            },
            { 
                answer: "Houston",
                points: 10,
                accept: ["Houston"],
                description: null,
            },            
            { 
                answer: "Minneapolis",
                points: 30,
                accept: ["Minneapolis"],
                description: null,
            },
            { 
                answer: "Rockland, ME",
                points: 85,
                accept: ["Rockland"],
                description: null,
            },            
            { 
                answer: "Buffalo",
                points: 60,
                accept: ["Buffalo"],
                description: null,
            },
            { 
                answer: "Fort Lauderdale",
                points: 60,
                accept: ["Fort Lauderdale"],
                description: null,
            },            
            { 
                answer: "Austin",
                points: 30,
                accept: ["Austin"],
                description: null,
            },
            { 
                answer: "Cincinnati",
                points: 60,
                accept: ["Cincinnati"],
                description: null,
            },            
            { 
                answer: "Columbus",
                points: 30,
                accept: ["Columbus"],
                description: null,
            },
            { 
                answer: "Montreal",
                points: 30,
                accept: ["Montreal"],
                description: null,
            },            
            { 
                answer: "Indianapolis",
                points: 30,
                accept: ["Indianapolis"],
                description: null,
            },
            { 
                answer: "Saint Louis",
                points: 30,
                accept: ["Saint Louis"],
                description: null,
            },
            { 
                answer: "Richmond",
                points: 30,
                accept: ["Richmond"],
                description: null,
            },
            { 
                answer: "Cleveland",
                points: 30,
                accept: ["Cleveland"],
                description: null,
            },
            { 
                answer: "Hyannis",
                points: 85,
                accept: ["Hyannis"],
                description: null,
            },
            { 
                answer: "Jacksonville",
                points: 30,
                accept: ["Jacksonville"],
                description: null,
            },
            { 
                answer: "Augusta, ME",
                points: 60,
                accept: ["Augusta"],
                description: null,
            },
            { 
                answer: "West Palm Beach",
                points: 60,
                accept: ["West Palm Beach", "Palm Beach"],
                description: null,
            },
            { 
                answer: "San Juan",
                points: 60,
                accept: ["San Juan"],
                description: null,
            },
            { 
                answer: "Paris",
                points: 10,
                accept: ["Paris"],
                description: null,
            },
            { 
                answer: "Dublin",
                points: 30,
                accept: ["Dublin"],
                description: null,
            },
            { 
                answer: "Dulles",
                points: 60,
                accept: ["Dulles"],
                description: null,
            },
            { 
                answer: "Lebanon, NH",
                points: 85,
                accept: ["Lebanon"],
                description: null,
            },
            { 
                answer: "Pheonix",
                points: 30,
                accept: ["Pheonix"],
                description: null,
            },
            { 
                answer: "Salt Lake City",
                points: 30,
                accept: ["Salt Lake City"],
                description: null,
            },
            { 
                answer: "Portland, OR",
                points: 30,
                accept: ["Portland"],
                description: null,
            },
            { 
                answer: "Amsterdam",
                points: 30,
                accept: ["Amsterdam"],
                description: null,
            },
            { 
                answer: "Islip, NY",
                points: 85,
                accept: ["Islip"],
                description: null,
            },
            { 
                answer: "Charleston",
                points: 60,
                accept: ["Charleston"],
                description: null,
            },
            { 
                answer: "Las Vegas",
                points: 30,
                accept: ["Las Vegas", "Vegas"],
                description: null,
            },
            { 
                answer: "Frankfurt",
                points: 30,
                accept: ["Frankfurt"],
                description: null,
            },
            { 
                answer: "Lisbon",
                points: 30,
                accept: ["Lisbon"],
                description: null,
            },
            { 
                answer: "Madrid",
                points: 30,
                accept: ["Madrid"],
                description: null,
            },
            { 
                answer: "Massena, NY",
                points: 85,
                accept: ["Massena"],
                description: null,
            },
            { 
                answer: "Fort Myers",
                points: 60,
                accept: ["fort myers"],
                description: null,
            },
            { 
                answer: "Rutland, VT",
                points: 85,
                accept: ["Rutland"],
                description: null,
            },
            { 
                answer: "Aruba",
                points: 85,
                accept: ["Aruba"],
                description: null,
            },
            { 
                answer: "Rochester",
                points: 60,
                accept: ["Rochester"],
                description: null,
            },
            { 
                answer: "Santo Domingo",
                points: 60,
                accept: ["Santo Domingo"],
                description: null,
            },
            { 
                answer: "Milwaukee",
                points: 60,
                accept: ["Milwaukee"],
                description: null,
            },
            { 
                answer: "Barcelona",
                points: 30,
                accept: ["Barcelona"],
                description: null,
            },
            { 
                answer: "Norfolk",
                points: 60,
                accept: ["Norfolk"],
                description: null,
            },
            { 
                answer: "Savannah",
                points: 60,
                accept: ["Savannah"],
                description: null,
            },
            { 
                answer: "Traverse City, MI",
                points: 85,
                accept: ["Traverse City"],
                description: null,
            },
            { 
                answer: "Bermuda",
                points: 60,
                accept: ["Bermuda"],
                description: null,
            },
            { 
                answer: "Louisville",
                points: 60,
                accept: ["Louisvill"],
                description: null,
            },
            { 
                answer: "Edinburgh",
                points: 85,
                accept: ["Edinburgh"],
                description: null,
            },
            { 
                answer: "Rome",
                points: 30,
                accept: ["Rome"],
                description: null,
            },
            { 
                answer: "Reykjavik",
                points: 60,
                accept: ["Reykjavik"],
                description: null,
            },
            { 
                answer: "Punta Cana, DR",
                points: 85,
                accept: ["Punta Cana"],
                description: null,
            },
            { 
                answer: "Saranac Lake, NY",
                points: 85,
                accept: ["Saranac Lake", "Saranac"],
                description: null,
            },
            { 
                answer: "Santiago de los Caballeros",
                points: 85,
                accept: ["Santiago", "Santiago de los Caballeros", "Caballeros"],
                description: null,
            },
            { 
                answer: "Syracuse",
                points: 60,
                accept: ["Syracuse"],
                description: null,
            },
            { 
                answer: "Zurich",
                points: 60,
                accept: ["Zurich"],
                description: null,
            },
            { 
                answer: "Cancun",
                points: 30,
                accept: ["Cancun"],
                description: null,
            },
            { 
                answer: "Madison",
                points: 60,
                accept: ["Madison"],
                description: null,
            },
            { 
                answer: "New Orleans",
                points: 30,
                accept: ["New Orleans"],
                description: null,
            },
            { 
                answer: "Bozeman, MT",
                points: 100,
                accept: ["Bozeman"],
                description: null,
            },
            { 
                answer: "Kansas City",
                points: 60,
                accept: ["Kansas City"],
                description: null,
            },
            { 
                answer: "Milan",
                points: 30,
                accept: ["Milan"],
                description: null,
            },
            { 
                answer: "Panama City",
                points: 85,
                accept: ["Panama City", "Panama"],
                description: null,
            },
            { 
                answer: "Calgary",
                points: 30,
                accept: ["Calgary"],
                description: null,
            },
            { 
                answer: "Abu Dhabi",
                points: 60,
                accept: ["Abu Dhabi"],
                description: null,
            },
            { 
                answer: "Daytona Beach",
                points: 60,
                accept: ["Daytona Beach"],
                description: null,
            },
            { 
                answer: "Halifax",
                points: 60,
                accept: ["Halifax"],
                description: null,
            },
            { 
                answer: "Mexico City",
                points: 30,
                accept: ["Mexico City"],
                description: null,
            },
            { 
                answer: "Ponta Delgada, PT",
                points: 85,
                accept: ["Ponta Delgada"],
                description: null,
            },
            { 
                answer: "Athens",
                points: 60,
                accept: ["Athens"],
                description: null,
            },
            { 
                answer: "Copenhagen",
                points: 60,
                accept: ["Copenhagen"],
                description: null,
            },
            { 
                answer: "Dallas",
                points: 10,
                accept: ["Dallas"],
                description: null,
            },
            { 
                answer: "Dubai",
                points: 60,
                accept: ["Dubai"],
                description: null,
            },
            { 
                answer: "Key West",
                points: 85,
                accept: ["Key West"],
                description: null,
            },
            { 
                answer: "Hong Kong",
                points: 60,
                accept: ["Hong Kong"],
                description: null,
            },
            { 
                answer: "Seoul",
                points: 30,
                accept: ["Seoul"],
                description: null,
            },
            { 
                answer: "Istanbul",
                points: 30,
                accept: ["Istanbul"],
                description: null,
            },
            { 
                answer: "Middletown, PA",
                points: 85,
                accept: ["Middletown", "Harrisburg"],
                description: null,
            },
            { 
                answer: "Munich",
                points: 30,
                accept: ["Munich"],
                description: null,
            },
            { 
                answer: "Tokyo",
                points: 30,
                accept: ["Tokyo"],
                description: null,
            },
            { 
                answer: "Presque Isle, ME",
                points: 100,
                accept: ["Presque", "Presque isle"],
                description: null,
            },
            { 
                answer: "San Salvador",
                points: 85,
                accept: ["San Salvador"],
                description: null,
            },
            { 
                answer: "Shannon, IE",
                points: 100,
                accept: ["Shannon"],
                description: null,
            },
            { 
                answer: "Ottawa",
                points: 30,
                accept: ["Ottawa"],
                description: null,
            },
            { 
                answer: "Vancouver",
                points: 30,
                accept: ["Vancouver"],
                description: null,
            },
            { 
                answer: "San Antonio",
                points: 60,
                accept: ["San Antonio"],
                description: null,
            },
            { 
                answer: "Vienna",
                points: 60,
                accept: ["Vienna"],
                description: null,
            },
            { 
                answer: "Vero Beach, FL",
                points: 85,
                accept: ["Vero", "Vero beach"],
                description: null,
            },
            { 
                answer: "Asheville",
                points: 60,
                accept: ["Asheville"],
                description: null,
            },
            { 
                answer: "Myrtle Beach",
                points: 60,
                accept: ["Myrtle Beach", "Myrtle"],
                description: null,
            },
            { 
                answer: "Doha",
                points: 85,
                accept: ["Doha"],
                description: null,
            },
            { 
                answer: "Sao Paulo",
                points: 60,
                accept: ["Sao Paulo"],
                description: null,
            },
            { 
                answer: "Hayden, CO",
                points: 85,
                accept: ["Hayden", "Steamboat", "Steamboat Springs"],
                description: null,
            },
            { 
                answer: "Honolulu",
                points: 30,
                accept: ["Honolulu"],
                description: "The longest domestic flight in the entire USA.",
            },
            { 
                answer: "Montego Bay",
                points: 30,
                accept: ["Montego Bay"],
                description: null,
            },
            { 
                answer: "Porto",
                points: 60,
                accept: ["Porto"],
                description: null,
            },
            { 
                answer: "Sarasota, FL",
                points: 85,
                accept: ["Sarasota"],
                description: null,
            },
            { 
                answer: "Tel Aviv-Yafo",
                points: 85,
                accept: ["Tel Aviv-Yafo", "Tel Aviv"],
                description: null,
            },
            { 
                answer: "Fort Walton, FL",
                points: 85,
                accept: ["Fort Walton"],
                description: null,
            },
            { 
                answer: "Bogota",
                points: 60,
                accept: ["Bogota"],
                description: null,
            },
            { 
                answer: "Guanacaste, Costa Rica",
                points: 85,
                accept: ["Guanacaste", "Liberia"],
                description: null,
            },
            { 
                answer: "Nice",
                points: 60,
                accept: ["Nice"],
                description: null,
            },
            { 
                answer: "Beijing",
                points: 60,
                accept: ["Beijing"],
                description: null,
            },
            { 
                answer: "Saint Thomas, US Virgin Islands",
                points: 85,
                accept: ["Saint Thomas"],
                description: null,
            },
            { 
                answer: "Knoxville",
                points: 60,
                accept: ["Knoxville"],
                description: null,
            },
            { 
                answer: "Anguilla",
                points: 85,
                accept: ["Anguilla"],
                description: null,
            },
            { 
                answer: "Des Moines",
                points: 60,
                accept: ["Des Moines"],
                description: null,
            },
            { 
                answer: "Grand Cayman Island",
                points: 85,
                accept: ["Grand Cayman Island", "Cayman Islands"],
                description: null,
            },
            { 
                answer: "Grand Rapids",
                points: 85,
                accept: ["Grand Rapids"],
                description: null,
            },
            { 
                answer: "Saint Lucia",
                points: 85,
                accept: ["Saint Lucia"],
                description: null,
            },
            { 
                answer: "Anchorage",
                points: 60,
                accept: ["Anchorage"],
                description: null,
            },
            { 
                answer: "Bridgetown, Barbados",
                points: 85,
                accept: ["Bridgetown"],
                description: null,
            },
            { 
                answer: "Cap Haitien",
                points: 85,
                accept: ["Cap Haitien"],
                description: null,
            },
            { 
                answer: "Green Bay",
                points: 85,
                accept: ["Green Bay"],
                description: null,
            },
            { 
                answer: "Hilton Head, SC",
                points: 85,
                accept: ["Hilton Head"],
                description: null,
            },
            { 
                answer: "Nassau",
                points: 85,
                accept: ["Nassau"],
                description: null,
            },
            { 
                answer: "Providenciales, Turks and Caicos",
                points: 85,
                accept: ["Providenciales"],
                description: null,
            },
            { 
                answer: "Puerto Plata, DR",
                points: 85,
                accept: ["Puerto Plata"],
                description: null,
            },
            { 
                answer: "South Bend",
                points: 100,
                accept: ["South Bend"],
                description: null,
            },
            { 
                answer: "Saint Maarten",
                points: 85,
                accept: ["Saint Maarten"],
                description: null,
            },
            { 
                answer: "Terceira, Portugal",
                points: 85,
                accept: ["Terceira"],
                description: null,
            },
            { 
                answer: "Jackson, WY",
                points: 85,
                accept: ["Jackson"],
                description: null,
            },
            { 
                answer: "Lexington",
                points: 60,
                accept: ["Lexington"],
                description: null,
            },
            { 
                answer: "Punta Gorda",
                points: 85,
                accept: ["Punta Gorda"],
                description: null,
            },
            { 
                answer: "Saint Petersburg",
                points: 85,
                accept: ["Saint Petersburg"],
                description: null,
            },
            { 
                answer: "Tallahassee",
                points: 60,
                accept: ["Tallahassee"],
                description: null,
            }
        ],
        incorrectAnswers: [],
        pointOverride: null,
    },
    {
        // Office 5/5
        prompt: "Name a restaurant within a 1/4 mile (400m) of the office",
        answers: [
            { 
                answer: "Passage to India",
                points: 30,
                accept: ["Passage to India"],
                description: null,
            },
            { 
                answer: "Just Salad",
                points: 10,
                accept: ["Just Salad"],
                description: null,
            },
            { 
                answer: "bom dough",
                points: 30,
                accept: ["bom dough"],
                description: null,
            },
            { 
                answer: "Bon Me",
                points: 10,
                accept: ["Bon Me"],
                description: null,
            },
            { 
                answer: "Tatte",
                points: 10,
                accept: ["Tatte"],
                description: null,
            },
            { 
                answer: "Cafe Beatrice",
                points: 60,
                accept: ["Cafe Beatrice"],
                description: null,
            },
            { 
                answer: "Geppetto",
                points: 85,
                accept: ["Geppetto"],
                description: null,
            },
            { 
                answer: "The Lexington",
                points: 85,
                accept: ["The Lexington", "Lexington"],
                description: null,
            },
            { 
                answer: "Lamplighter",
                points: 60,
                accept: ["Lamplighter"],
                description: null,
            },
            { 
                answer: "Tap 151 Bar and Grill",
                points: 60,
                accept: ["Tap 151 Bar and Grill", "Tap 151"],
                description: null,
            },
            { 
                answer: "The Scoop N Scootery",
                points: 15,
                accept: ["The Scoop N Scootery"],
                description: "Not really a restaurant."
            },
            { 
                answer: "Anthony's Pizza",
                points: 100,
                accept: [
                    "Anthony's Pizza",
                    "Anthonys pizza",
                    "Anthony's",
                    "Anthonys"
                ],
                description: null,
            },
            { 
                answer: "Arams #2 House of Pizza",
                points: 85,
                accept: ["Arams #2 House of Pizza", "Arams", "Arams house of pizza"],
                description: null,
            },
            { 
                answer: "Sweet Touch Cafe",
                points: 85,
                accept: ["Sweet Touch Cafe", "Sweet touch"],
                description: null,
            },
            { 
                answer: "Blaze Pizza",
                points: 10,
                accept: ["Blaze Pizza", "Blaze"],
                description: null,
            },
            { 
                answer: "Love Art Sushi",
                points: 10,
                accept: ["Love Art Sushi"],
                description: null,
            },
            { 
                answer: "Pokeworks",
                points: 30,
                accept: ["Pokeworks"],
                description: null,
            },
            { 
                answer: "Anoush'ella",
                points: 60,
                accept: ["Anoush'ella", "Anoushella"],
                description: null,
            },
            { 
                answer: "Amba",
                points: 60,
                accept: ["Amba"],
                description: null,
            },
            { 
                answer: "Taco Bell",
                points: 30,
                accept: ["Taco Bell"],
                description: null,
            },
            { 
                answer: "Sapporo Ramen",
                points: 85,
                accept: ["Sapporo Ramen"],
                description: null,
            },
            { 
                answer: "Cheesecake Factory",
                points: 60,
                accept: ["Cheesecake Factory", "Cheescake"],
                description: null,
            },
            { 
                answer: "Monteverdi",
                points: 85,
                accept: ["Monteverdi"],
                description: null,
            },
            { 
                answer: "Scull & Keel",
                points: 85,
                accept: ["Scull & Keel", "Scull", "Keel"],
                description: null,
            },
            { 
                answer: "Bambara Cambridge",
                points: 85,
                accept: ["Bambara Cambridge", "Bambara"],
                description: null,
            },
            { 
                answer: "Chilacates",
                points: 85,
                accept: ["Chilacates"],
                description: null,
            },
            { 
                answer: "Gato Exotico",
                points: 60,
                accept: ["Gato Exotico", "El Gato", "Gato"],
                description: null,
            },
            { 
                answer: "NuBurger",
                points: 85,
                accept: ["NuBurger"],
                description: null,
            },
            { 
                answer: "Dalmoros Fresh Italian",
                points: 85,
                accept: ["Dalmoros Fresh Italian", "Dalmoros"],
                description: null,
            },
            { 
                answer: "Lala's Neopolotan-ish Pizza",
                points: 85,
                accept: ["Lala's Neopolotan-ish Pizza", "Lala's", "Lalas"],
                description: null,
            },
            { 
                answer: "InChu",
                points: 85,
                accept: ["InChu"],
                description: null,
            },
            { 
                answer: "Caffe Nero",
                points: 60,
                accept: ["Caffe Nero", "Cafe Nero", "Nero", "Nerro"],
                description: null,
            },
        ],
        incorrectAnswers: [
            {
                hint: "Too far away.",
                accept: [
                    "Tenoche",
                    "The Helmand",
                    "Helmand",
                    "Kiin Thai",
                    "Kiin Thai Sushi",
                    "Boca Grande",
                    "Boca Grande Taqueria"
                ]
            },
            {
                hint: "No longer operating",
                accept: ["Second Street Cafe", "Chipotle", "Panda Express"]
            }
        ],
        pointOverride: null,
    },
    {
        // Personal 5/5
        prompt: "Name the hometown of any Kriller",
        description: "Think about how they would answer 'Where are you from?'",
        answers: [
            { 
                answer: "Ottawa",
                points: 30,
                accept: ["Ottawa"],
                description: null,
            },
            { 
                answer: "Mississauga",
                points: 60,
                accept: ["Mississauga"],
                description: null,
            },
            { 
                answer: "North York",
                points: 85,
                accept: ["North York"],
                description: null,
            },
            { 
                answer: "Toronto",
                points: 10,
                accept: ["Toronto"],
                description: null,
            },
            { 
                answer: "Waterloo",
                points: 30,
                accept: ["Waterloo"],
                description: null,
            },
            { 
                answer: "Markham",
                points: 60,
                accept: ["Markham"],
                description: null,
            },
            { 
                answer: "Maplewood",
                points: 60,
                accept: ["Maplewood"],
                description: null,
            },
            { 
                answer: "Rimbey",
                points: 60,
                accept: ["Rimbey"],
                description: "You were paying attention last week!",
            },
            { 
                answer: "North Windham",
                points: 100,
                accept: ["North Windham", "North Windam", "Windham"],
                description: null,
            },
            { 
                answer: "Calgary",
                points: 30,
                accept: ["Calgary"],
                description: null,
            },
            { 
                answer: "Acton",
                points: 85,
                accept: ["Acton"],
                description: null,
            },
            { 
                answer: "Windsor",
                points: 100,
                accept: ["Windsor"],
                description: null,
            },
            { 
                answer: "Brampton",
                points: 30,
                accept: ["Brampton"],
                description: null,
            },
        ],
        incorrectAnswers: [
            {
                hint: "Try a city or town, not a state.",
                accept: [
                    "Maine",
                    "Massachusetts",
                    "Mass",
                    "New Jersey",
                    "Jersey"
                ]
            },            
            {
                hint: "Try a city or town, not a province.",
                accept: [
                    "Ontario",
                    "Alberta"
                ]
            }
        ],
        pointOverride: null,
    },
    {
        // Canada
        prompt: "Name a lyric in 'O Canada' (in English)",
        answers: [
            { 
                answer: "O",
                points: 15,
                accept: ["O"],
                description: null,
            },
            { 
                answer: "Canada",
                points: 15,
                accept: ["Canada"],
                description: "This was all you could think of?",
            },
            { 
                answer: "our",
                points: 10,
                accept: ["our"],
                description: null,
            },
            { 
                answer: "home",
                points: 10,
                accept: ["home"],
                description: null,
            },            { 
                answer: "and",
                points: 10,
                accept: ["and"],
                description: null,
            },
            { 
                answer: "native",
                points: 60,
                accept: ["native"],
                description: null,
            },            { 
                answer: "land",
                points: 30,
                accept: ["land"],
                description: null,
            },
            { 
                answer: "true",
                points: 30,
                accept: ["true"],
                description: null,
            },            { 
                answer: "patriot",
                points: 60,
                accept: ["patriot"],
                description: null,
            },
            { 
                answer: "love",
                points: 60,
                accept: ["love"],
                description: null,
            },            { 
                answer: "in",
                points: 10,
                accept: ["in"],
                description: null,
            },
            { 
                answer: "all",
                points: 10,
                accept: ["all"],
                description: null,
            },            { 
                answer: "of",
                points: 10,
                accept: ["of"],
                description: null,
            },
            { 
                answer: "us",
                points: 10,
                accept: ["us"],
                description: null,
            },            { 
                answer: "command",
                points: 60,
                accept: ["command"],
                description: null,
            },
            { 
                answer: "with",
                points: 10,
                accept: ["with"],
                description: null,
            },            { 
                answer: "glowing",
                points: 100,
                accept: ["glowing"],
                description: null,
            },
            { 
                answer: "hearts",
                points: 85,
                accept: ["hearts"],
                description: null,
            },            { 
                answer: "we",
                points: 10,
                accept: ["we"],
                description: null,
            },
            { 
                answer: "see",
                points: 10,
                accept: ["see"],
                description: null,
            },            { 
                answer: "thee",
                points: 30,
                accept: ["thee"],
                description: null,
            },
            { 
                answer: "rise",
                points: 30,
                accept: ["rise"],
                description: null,
            },
            { 
                answer: "the",
                points: 10,
                accept: ["the"],
                description: null,
            },
            { 
                answer: "true",
                points: 60,
                accept: ["true"],
                description: null,
            },
            { 
                answer: "north",
                points: 60,
                accept: ["north"],
                description: null,
            },            { 
                answer: "strong",
                points: 85,
                accept: ["strong"],
                description: null,
            },
            { 
                answer: "from",
                points: 30,
                accept: ["from"],
                description: null,
            },
            { 
                answer: "far",
                points: 30,
                accept: ["far"],
                description: null,
            },
            { 
                answer: "wide",
                points: 60,
                accept: ["wide"],
                description: null,
            },
            { 
                answer: "stand",
                points: 30,
                accept: ["stand"],
                description: null,
            },
            { 
                answer: "on",
                points: 10,
                accept: ["on"],
                description: null,
            },
            { 
                answer: "guard",
                points: 30,
                accept: ["guard"],
                description: null,
            },
            { 
                answer: "for",
                points: 10,
                accept: ["for"],
                description: null,
            },
            { 
                answer: "god",
                points: 85,
                accept: ["god"],
                description: null,
            },
            { 
                answer: "glorious",
                points: 100,
                accept: ["glorious"],
                description: null,
            },            { 
                answer: "keep",
                points: 10,
                accept: ["keep"],
                description: null,
            },
            { 
                answer: "free",
                points: 60,
                accept: ["free"],
                description: null,
            },
            { 
                answer: "sons",
                points: 15,
                accept: ["sons"],
                description: "A retired lyric since 2018",
            },
        ],
        incorrectAnswers: [],
        pointOverride: null,
    },
    // {
    //     // Local Geography 3/5
    //     prompt: "Name a neighbourhood or area in Cambridge",
    //     answers: [
    //         { 
    //             answer: "Cambridge Crossing",
    //             points: 10,
    //             accept: ["Cambridge Crossing"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Lechmere Square",
    //             points: 10,
    //             accept: ["Lechmere Square", "Lechmere"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Central Square",
    //             points: 10,
    //             accept: ["Central Square", "Central"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Harvard Square",
    //             points: 30,
    //             accept: ["Harvard Square", "Harvard"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Kendall Square",
    //             points: 10,
    //             accept: ["Kendall Square", "Kendall"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Porter Square",
    //             points: 60,
    //             accept: ["Porter Square", "Porter"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Inman Square",
    //             points: 60,
    //             accept: ["Inman", "Inman Square"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Huron Village",
    //             points: 85,
    //             accept: ["Huron Village"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Avon Hill",
    //             points: 85,
    //             accept: ["Avon Hill"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Observatory Hill",
    //             points: 85,
    //             accept: ["Observatory Hill"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Tory Hill",
    //             points: 85,
    //             accept: ["Tory Hill"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Alewife",
    //             points: 60,
    //             accept: ["Alewife"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Fresh Pond",
    //             points: 85,
    //             accept: ["Fresh Pond"],
    //             description: null,
    //         },
    //         { 
    //             answer: "East Cambridge",
    //             points: 10,
    //             accept: ["East Cambridge"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Area 2/MIT",
    //             points: 60,
    //             accept: ["Area 2", "Area two", "MIT", "Area 2/MIT"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Wellington-Harrington",
    //             points: 85,
    //             accept: ["Wellington-Harrington", "Wellington Harrington", "Wellington", "Harrington"],
    //             description: null,
    //         },
    //         { 
    //             answer: "The Port/Area 4",
    //             points: 60,
    //             accept: ["The Port/Area 4", "The Port", "Area 4", "Area four"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Cambridgeport",
    //             points: 60,
    //             accept: ["Cambridgeport"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Mid-Cambridge",
    //             points: 60,
    //             accept: ["Mid-Cambridge", "MidCambridge", "Mid Cambridge"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Riverside",
    //             points: 85,
    //             accept: ["Riverside"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Strawberry Hill",
    //             points: 100,
    //             accept: ["Strawberry Hill"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Cambridge Highlands",
    //             points: 85,
    //             accept: ["Cambridge Highlands"],
    //             description: null,
    //         },
    //         { 
    //             answer: "North Cambridge",
    //             points: 60,
    //             accept: ["North Cambridge"],
    //             description: null,
    //         },
    //         { 
    //             answer: "West Cambridge",
    //             points: 60,
    //             accept: ["West Cambridge"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Neighborhood Nine",
    //             points: 85,
    //             accept: ["Neighborhood Nine", "Neighborhood 9"],
    //             description: null,
    //         },
    //         { 
    //             answer: "Baldwin",
    //             points: 85,
    //             accept: ["Baldwin"],
    //             description: null,
    //         },
    //     ],
    //     incorrectAnswers: [],
    //     pointOverride: null,
    // },
    {
        // Local Sports 4/5
        prompt: "Name a major league sports team that plays in any Kriller's home state/province",
        description: "(Basketball, Football, Baseball, and Hockey)",
        answers: [
            { 
                answer: "Edmonton Oilers",
                points: 60,
                accept: ["Oilers", "Edmonton Oilers"],
                description: null,
            },
            { 
                answer: "Calgary Flames",
                points: 85,
                accept: ["Flames", "Calgary Flames"],
                description: null,
            },
            { 
                answer: "Toronto Raptors",
                points: 30,
                accept: ["Raptors", "Toronto Raptors"],
                description: null,
            },
            { 
                answer: "Toronto Maple Leafs",
                points: 10,
                accept: ["Maple Leafs", "Leafs", "Toronto Maple Leafs"],
                description: null,
            },
            { 
                answer: "Toronto Blue Jays",
                points: 10,
                accept: ["Blue jays", "jays", "Toronto Blue Jays"],
                description: null,
            },
            { 
                answer: "Boston Celtics",
                points: 10,
                accept: ["celtics", "Boston Celtics"],
                description: null,
            },
            { 
                answer: "New England Patriots",
                points: 30,
                accept: ["Patriots", "pats", "New England Patriots"],
                description: null,
            },
            { 
                answer: "Ottawa Senators",
                points: 85,
                accept: ["Ottawa Senators", "Senators", "Sens"],
                description: null,
            },
            { 
                answer: "Boston Bruins",
                points: 30,
                accept: ["Bruins", "Boston Bruins"],
                description: null,
            },
            { 
                answer: "Boston Red Sox",
                points: 10,
                accept: ["Red sox", "sox", "Boston Red Sox"],
                description: null,
            },
            { 
                answer: "New York Jets",
                points: 100,
                accept: ["Jets", "New York Jets"],
                description: "Both the Jets and Giants play in New Jersey.",
            },
            { 
                answer: "New York Giants",
                points: 100,
                accept: ["Giants", "New York Giants"],
                description: null,
            },
            { 
                answer: "New Jersey Devils",
                points: 60,
                accept: ["Devils", "New Jersey Devils"],
                description: null,
            },
            { 
                answer: "New Jersey Nets",
                points: 15,
                accept: ["Nets", "New Jersey Nets"],
                description: "Used to play in New Jersey before moving to Brooklyn.",
            },
        ],
        incorrectAnswers: [],
        pointOverride: null,
    },
    {
        // Personal 5/5
        prompt: "Name any Kriller's Birthday",
        description: "Answer with only the month and day. Ex: 'January 1'",
        answers: [
            { 
                answer: "January 4",
                points: 85,
                accept: ["January 4"],
                description: null,
            },
            { 
                answer: "January 15",
                points: 85,
                accept: ["January 15"],
                description: null,
            },
            { 
                answer: "January 17",
                points: 85,
                accept: ["January 17"],
                description: null,
            },
            { 
                answer: "February 4",
                points: 100,
                accept: ["February 4"],
                description: null,
            },
            { 
                answer: "February 15",
                points: 85,
                accept: ["February 15"],
                description: null,
            },
            { 
                answer: "March 12",
                points: 100,
                accept: ["March 12"],
                description: null,
            },
            { 
                answer: "April 16",
                points: 30,
                accept: ["April 16"],
                description: null,
            },
            { 
                answer: "April 29",
                points: 30,
                accept: ["April 29"],
                description: null,
            },
            { 
                answer: "May 11",
                points: 85,
                accept: ["May 11"],
                description: null,
            },
            { 
                answer: "May 23",
                points: 85,
                accept: ["May 23"],
                description: null,
            },
            { 
                answer: "July 1",
                points: 10,
                accept: ["July 1"],
                description: null,
            },
            { 
                answer: "August 7",
                points: 85,
                accept: ["August 7"],
                description: null,
            },
            { 
                answer: "August 23",
                points: 30,
                accept: ["August 23"],
                description: null,
            },
        ],
        incorrectAnswers: [
            {
                hint: "Try a city or town, not a state.",
                accept: [
                    "Maine",
                    "Massachusetts",
                    "Mass",
                    "New Jersey",
                    "Jersey"
                ]
            },            
            {
                hint: "Try a city or town, not a province.",
                accept: [
                    "Ontario",
                    "Alberta"
                ]
            }
        ],
        pointOverride: null,
    },
    {
        // Meta
        prompt: "Name a 100 point answer from the previous two Crillions",
        description: "Second chance! More points for answers that nobody guessed.",
        answers: [
            { 
                answer: "Ghent",
                points: 100,
                accept: ["Ghent"],
                description: null,
            },
            { 
                answer: "Bengaluru",
                points: 60,
                accept: ["Bengaluru", "Bangalore"],
                description: null,
            },
            { 
                answer: "New England Free Jacks",
                points: 100,
                accept: ["Free Jacks", "New England Free Jacks", "Jacks"],
                description: null,
            },
            { 
                answer: "Boston Cannons",
                points: 100,
                accept: ["Boston Cannons", "Cannons"],
                description: null,
            },
            { 
                answer: "Navid",
                points: 30,
                accept: ["Navid"],
                description: null,
            },
            { 
                answer: "LoDolceVita",
                points: 100,
                accept: ["LoDolceVita"],
                description: null,
            },
            { 
                answer: "North York",
                points: 100,
                accept: ["North York"],
                description: null,
            },
            { 
                answer: "Chinook",
                points: 100,
                accept: ["Chinook"],
                description: null,
            },
            { 
                answer: "Garburator",
                points: 100,
                accept: ["Garburator"],
                description: null,
            },
            { 
                answer: "Ahlie",
                points: 100,
                accept: ["Ahlie"],
                description: null,
            },
            { 
                answer: "Lincoln Woods State Park",
                points: 85,
                accept: ["Lincoln Woods State Park", "Lincoln Woods", "Outdoor bouldering", "Bouldering"],
                description: null,
            },
            { 
                answer: "Puma",
                points: 100,
                accept: ["Puma"],
                description: null,
            },
            { 
                answer: "Shoebill",
                points: 60,
                accept: ["Shoebill"],
                description: null,
            },
            { 
                answer: "Suffolk Downs",
                points: 100,
                accept: ["Suffolk Downs", "Suffolk"],
                description: null,
            },
            { 
                answer: "Chiswick Road",
                points: 100,
                accept: ["Chiswick Road", "Chiswick"],
                description: null,
            },
            { 
                answer: "Tappan Street",
                points: 100,
                accept: ["Tappan Street", "Tappan"],
                description: null,
            },
            { 
                answer: "Pears",
                points: 100,
                accept: ["Pears"],
                description: null,
            },
            { 
                answer: "Blueberries",
                points: 100,
                accept: ["Blueberries", "Blueberry"],
                description: null,
            },
            { 
                answer: "Wayne",
                points: 60,
                accept: ["Wayne"],
                description: null,
            },
            { 
                answer: "Norwell",
                points: 100,
                accept: ["Norwell"],
                description: null,
            },
            { 
                answer: "Sudbury",
                points: 100,
                accept: ["Sudbury"],
                description: null,
            },
            { 
                answer: "Whitman",
                points: 100,
                accept: ["Whitman"],
                description: null,
            },
            { 
                answer: "Stephanie",
                points: 100,
                accept: ["Stephanie"],
                description: null,
            },
            { 
                answer: "Luke",
                points: 100,
                accept: ["Luke"],
                description: null,
            },
            { 
                answer: "Berlin",
                points: 30,
                accept: ["Berlin"],
                description: null,
            },
        ],
        incorrectAnswers: [],
        pointOverride: null,
    },
];

